version: "3.8"

services:
    # --- SERVIÇO DO BACKEND (API TYPESCRIPT) ---
  backend:
    # CORREÇÃO: Aponta para a pasta correta do backend
    build: ./meidesaqua-backend
    container_name: meidesaqua-backend
    ports:
      # CORREÇÃO: A porta da API agora é 3001
      - "3001:3001"
    depends_on:
      - db
    # Diz ao compose para carregar variáveis de um arquivo chamado .env.production
    env_file:
      - ./.env.production 
    restart: always

  # --- SERVIÇO DO FRONTEND (SITE NEXT.JS) ---
  frontend:
    build: ./meidesaqua-frontend
    container_name: meidesaqua-frontend
    ports:
      # Expõe a porta 3000 do contêiner para a porta 3000 da sua máquina.
      - "3000:3000"
    # Garante que o frontend só suba depois que o backend estiver pronto.
    depends_on:
      - backend
    # Passa a URL do backend para o frontend.
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    restart: always

  # --- SERVIÇO DO BANCO DE DADOS ---
  db:
    # CORREÇÃO: Usando a imagem oficial do MySQL para corresponder ao driver do backend.
    image: mysql:8.0
    container_name: meidesaqua-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER} # CORREÇÃO: Usuário consistente com o backend.
      MYSQL_PASSWORD: ${DB_PASSWORD} # CORREÇÃO: Senha consistente com o backend.
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      # Mapeia a porta do MySQL para acesso externo (opcional, bom para debug).
      - "3306:3306"
    volumes:
      # Garante que os dados do banco não sejam perdidos.
      - mysql_data:/var/lib/mysql

# Define o volume nomeado para o banco de dados
volumes:
  mysql_data: